name: Test HostForge

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Python syntax check
      run: |
        python -m py_compile backend/app.py

    - name: Test Flask application startup
      run: |
        cd backend
        timeout 10s python app.py || true
        cd ..

    - name: Check file structure
      run: |
        # Check if required files exist
        if (!(Test-Path "backend/app.py")) { exit 1 }
        if (!(Test-Path "backend/requirements.txt")) { exit 1 }
        if (!(Test-Path "frontend/index.html")) { exit 1 }
        if (!(Test-Path "frontend/style.css")) { exit 1 }
        if (!(Test-Path "frontend/script.js")) { exit 1 }
        if (!(Test-Path "start_hostforge.bat")) { exit 1 }
        if (!(Test-Path "README.md")) { exit 1 }
        if (!(Test-Path ".gitignore")) { exit 1 }

    - name: Validate HTML
      run: |
        # Install html5validator
        pip install html5validator
        # Validate HTML files
        html5validator --root frontend/ 